(()=>{const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const loader=$("#loader"),pct=$("#loadPct"),bar=$(".loadbar i");let n=0;const t=setInterval(()=>{n=Math.min(100,n+Math.floor(Math.random()*9)+4);pct.textContent=n+"%";bar.style.width=n+"%";if(n>=100){clearInterval(t);setTimeout(()=>{loader.style.opacity=0;loader.style.visibility="hidden"},350)}},65);
const menu=$(".menu"),mobile=$(".mobile-menu");menu?.addEventListener("click",()=>{let o=mobile.classList.toggle("open");menu.textContent=o?"×":"☰"});$$(".mobile-menu a").forEach(a=>a.onclick=()=>{mobile.classList.remove("open");menu.textContent="☰"});
const ro=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("show");ro.unobserve(e.target)}}),{threshold:.12});$$(".reveal").forEach((e,i)=>{e.style.transitionDelay=Math.min(i%6,5)*65+"ms";ro.observe(e)});
const sections=$$("main section[id]"),links=$$(".nav nav a");new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)links.forEach(l=>l.classList.toggle("active",l.getAttribute("href")==="#"+e.target.id))}),{rootMargin:"-35% 0px -55%"}).observe;sections.forEach(s=>new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)links.forEach(l=>l.classList.toggle("active",l.getAttribute("href")==="#"+e.target.id))}),{rootMargin:"-35% 0px -55%"}).observe(s));
$$("[data-n]").forEach(el=>{let done=false;new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting&&!done){done=true;let target=+el.dataset.n,s=el.dataset.s||"",st=performance.now();let f=x=>{let p=Math.min((x-st)/1000,1),q=1-Math.pow(1-p,3);el.textContent=Math.round(target*q)+s;if(p<1)requestAnimationFrame(f)};requestAnimationFrame(f)}}),{threshold:.55}).observe(el)});
const line=$(".scrollbar i"),nav=$(".nav");addEventListener("scroll",()=>{let m=document.documentElement.scrollHeight-innerHeight;line.style.width=(m?scrollY/m*100:0)+"%";nav.classList.toggle("scrolled",scrollY>20)},{passive:true});
const c=$("#particles"),ctx=c?.getContext("2d");let W,H,ps=[];function resize(){if(!ctx)return;let d=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;c.width=W*d;c.height=H*d;c.style.width=W+"px";c.style.height=H+"px";ctx.setTransform(d,0,0,d,0,0);ps=Array.from({length:Math.min(75,Math.max(28,Math.floor(W/18)))},()=>({x:Math.random()*W,y:Math.random()*H,r:.4+Math.random()*1.2,v:.06+Math.random()*.24,a:.08+Math.random()*.28}))}function tick(){if(!ctx)return;ctx.clearRect(0,0,W,H);ctx.fillStyle="#b8f000";ps.forEach(p=>{p.y-=p.v;if(p.y<0)p.y=H;ctx.globalAlpha=p.a;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,7);ctx.fill()});requestAnimationFrame(tick)}resize();tick();addEventListener("resize",resize);
const cur=$(".cursor");if(cur&&matchMedia("(pointer:fine)").matches){addEventListener("mousemove",e=>{cur.style.left=e.clientX+"px";cur.style.top=e.clientY+"px"});$$("a,.tool,.project,.score").forEach(e=>{e.onmouseenter=()=>{cur.style.width="30px";cur.style.height="30px"};e.onmouseleave=()=>{cur.style.width="18px";cur.style.height="18px"}})}
if(innerWidth>900&&matchMedia("(pointer:fine)").matches)$$(".tool,.project,.score").forEach(el=>{el.onmousemove=e=>{let r=el.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;el.style.transform=`perspective(800px) rotateX(${y*-3}deg) rotateY(${x*4}deg) translateY(-4px)`};el.onmouseleave=()=>el.style.transform=""});
})();